/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package io.yoyolabs.org.apache.avro.mapred.tether;
@SuppressWarnings("all")
@io.yoyolabs.org.apache.avro.specific.AvroGenerated
public enum TaskType {
  MAP, REDUCE  ;
  public static final io.yoyolabs.org.apache.avro.Schema SCHEMA$ = new io.yoyolabs.org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"TaskType\",\"namespace\":\"io.yoyolabs.org.apache.avro.mapred.tether\",\"symbols\":[\"MAP\",\"REDUCE\"]}");
  public static io.yoyolabs.org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
