/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package io.yoyolabs.org.apache.avro.ipc;
@SuppressWarnings("all")
@io.yoyolabs.org.apache.avro.specific.AvroGenerated
public enum HandshakeMatch {
  BOTH, CLIENT, NONE  ;
  public static final io.yoyolabs.org.apache.avro.Schema SCHEMA$ = new io.yoyolabs.org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"HandshakeMatch\",\"namespace\":\"org.apache.avro.ipc\",\"symbols\":[\"BOTH\",\"CLIENT\",\"NONE\"]}");
  public static io.yoyolabs.org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
