/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package io.yoyolabs.org.apache.avro.ipc;
@SuppressWarnings("all")
@io.yoyolabs.org.apache.avro.specific.FixedSize(16)
@io.yoyolabs.org.apache.avro.specific.AvroGenerated
public class MD5 extends io.yoyolabs.org.apache.avro.specific.SpecificFixed {
  private static final long serialVersionUID = 6731146766938681575L;
  public static final io.yoyolabs.org.apache.avro.Schema SCHEMA$ = new io.yoyolabs.org.apache.avro.Schema.Parser().parse("{\"type\":\"fixed\",\"name\":\"MD5\",\"namespace\":\"org.apache.avro.ipc\",\"size\":16}");
  public static io.yoyolabs.org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  public io.yoyolabs.org.apache.avro.Schema getSchema() { return SCHEMA$; }

  /** Creates a new MD5 */
  public MD5() {
    super();
  }

  /**
   * Creates a new MD5 with the given bytes.
   * @param bytes The bytes to create the new MD5.
   */
  public MD5(byte[] bytes) {
    super(bytes);
  }

  private static final io.yoyolabs.org.apache.avro.io.DatumWriter
    WRITER$ = new io.yoyolabs.org.apache.avro.specific.SpecificDatumWriter<MD5>(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, io.yoyolabs.org.apache.avro.specific.SpecificData.getEncoder(out));
  }

  private static final io.yoyolabs.org.apache.avro.io.DatumReader
    READER$ = new io.yoyolabs.org.apache.avro.specific.SpecificDatumReader<MD5>(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, io.yoyolabs.org.apache.avro.specific.SpecificData.getDecoder(in));
  }

}
